In [1]:
import pandas as pd
import os
from pathlib import Path

In [2]:
# get current and parent directories using pathlib
curr_dir = Path(os.getcwd())
parent_dir = curr_dir.parents[0]
print('current directory: ' + str(curr_dir) + '\nparent directory:  ' + str(parent_dir))

current directory: C:\Users\habib\OneDrive\Documents\ANALYTICS\Github\Project-1---Crime-Demographics-and-City-Response\Liz
parent directory:  C:\Users\habib\OneDrive\Documents\ANALYTICS\Github\Project-1---Crime-Demographics-and-City-Response

In [3]:
# remove dollar signs and commas
def clean_numeric_str(curr_str):
    if isinstance(curr_str, str):
        return(curr_str.replace('$', '').replace(',', '').replace('%', ''))
    return(curr_str)

In [4]:
# rental csv is a kaggle dataset available here
# https://www.kaggle.com/rajacsp/toronto-apartment-price
#rental_csv = os.path.join(parent_dir, 'Resources', 'Toronto_apartment_rentals_2018.csv')
#rental_df = pd.read_csv(rental_csv, thousands=',')

# clean up currency data types
#rental_df['Price'] = rental_df['Price'].apply(clean_numeric_str).astype('float')

# check data types
#rental_df.dtypes

# see header
#rental_df.head()

# DO NOT USE THIS DATASET... NOT ENOUGH TORONTO DATA POINTS, NO SAMPLING METHOD PROVIDED. NOT VERIFIED INFORMATION.

In [5]:
# crime rate dataset
crime_csv = os.path.join(curr_dir, 'Resources', 'Neighbourhood_Crime_Rates.csv')
crime_df = pd.read_csv(crime_csv)
crime_df = crime_df.drop(['_id','OBJECTID'], axis=1)
crime_df.rename(columns = {'Hood_ID':'Neighbourhood Number'}, inplace = True) 
crime_df.sort_values(by='Neighbourhood Number')
# crime_df['Neighbourhood Number'].dtype

,Neighbourhood,Neighbourhood Number,Population,Assault_2014,Assault_2015,Assault_2016,Assault_2017,Assault_2018,Assault_2019,Assault_AVG,...,TheftOver_2016,TheftOver_2017,TheftOver_2018,TheftOver_2019,TheftOver_AVG,TheftOver_CHG,TheftOver_Rate_2019,Shape__Area,Shape__Length,geometry
26,West Humber-Clairville,1,33312,300,310,307,307,322,265,301.8,...,41,58,52,63,52.2,0.21,189.1,3.014532e+07,27924.196970,"{u'type': u'Polygon', u'coordinates': (((-79.5..."
83,Mount Olive-Silverstone-Jamestown,2,32954,236,234,270,273,254,268,255.8,...,4,1,3,9,4.5,2.00,27.3,4.637542e+06,12954.664120,"{u'type': u'Polygon', u'coordinates': (((-79.6..."
132,Thistletown-Beaumond Heights,3,10360,56,52,39,51,50,74,53.7,...,1,4,2,3,2.3,0.50,29.0,3.339481e+06,10828.444480,"{u'type': u'Polygon', u'coordinates': (((-79.5..."
88,Rexdale-Kipling,4,10529,49,59,77,87,78,62,68.7,...,0,1,3,3,1.7,0.00,28.5,2.505576e+06,7067.058509,"{u'type': u'Polygon', u'coordinates': (((-79.5..."
63,Elms-Old Rexdale,5,9456,40,50,61,58,51,67,54.5,...,0,2,1,4,1.5,3.00,42.3,2.931145e+06,9356.687072,"{u'type': u'Polygon', u'coordinates': (((-79.5..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25,West Hill,136,27392,343,395,423,400,420,431,402.0,...,8,10,5,4,6.7,-0.20,14.6,9.625440e+06,14976.571770,"{u'type': u'Polygon', u'coordinates': (((-79.2..."
96,Woburn,137,53485,352,395,365,400,369,427,384.7,...,14,23,13,8,13.7,-0.38,15.0,1.233407e+07,18111.264990,"{u'type': u'Polygon', u'coordinates': (((-79.2..."
62,Eglinton East,138,22776,179,173,201,198,181,194,187.7,...,6,1,6,8,5.2,0.33,35.1,3.223146e+06,10012.866980,"{u'type': u'Polygon', u'coordinates': (((-79.2..."
139,Scarborough Village,139,16724,161,153,192,152,178,175,168.5,...,2,4,3,2,2.7,-0.33,12.0,3.151015e+06,7922.764442,"{u'type': u'Polygon', u'coordinates': (((-79.2..."
21,Guildwood,140,9917,52,38,43,41,47,28,41.5,...,1,4,1,1,1.7,0.00,10.1,3.804331e+06,9830.064411,"{u'type': u'Polygon', u'coordinates': (((-79.2..."

In [6]:
# 2016 census data by Toronto neighbourhood available in the City of Toronto Open Data Portal
# https://open.toronto.ca/dataset/neighbourhood-profiles/
census_csv = os.path.join(curr_dir, 'Resources', 'neighbourhoods-profiles-2016-csv-transposed.csv')
census_df = pd.read_csv(census_csv)

# clean up numeric data types
for column in census_df:
    try:
        census_df[column] = census_df[column].apply(clean_numeric_str).astype('float')
    except:
        continue

census_df = census_df.drop(0)
census_df['Neighbourhood Number'] = census_df['Neighbourhood Number'].astype('int64')
census_df.sort_values(by='Neighbourhood Number')
# census_df['Neighbourhood Number'].dtype

,Neighbourhood,Neighbourhood Number,TSNS2020 Designation,"Population, 2016","Population, 2011",Population Change 2011-2016,Total private dwellings,Private dwellings occupied by usual residents,Population density per square kilometre,Land area in square kilometres,...,Total - Mobility status 1 year ago - 25% sample data|Movers|Migrants|External migrants,Total - Mobility status 5 years ago - 25% sample data,Total - Mobility status 5 years ago - 25% sample data|Non-movers,Total - Mobility status 5 years ago - 25% sample data|Movers,Total - Mobility status 5 years ago - 25% sample data|Movers|Non-migrants,Total - Mobility status 5 years ago - 25% sample data|Movers|Migrants,Total - Mobility status 5 years ago - 25% sample data|Movers|Migrants|Internal migrants,Total - Mobility status 5 years ago - 25% sample data|Movers|Migrants|Internal migrants|Intraprovincial migrants,Total - Mobility status 5 years ago - 25% sample data|Movers|Migrants|Internal migrants|Interprovincial migrants,Total - Mobility status 5 years ago - 25% sample data|Movers|Migrants|External migrants
125,West Humber-Clairville,1,No Designation,33312.0,34100.0,-2.3,11045.0,10285.0,1117.0,29.81,...,875.0,31330.0,20390.0,10945.0,6195.0,4745.0,1690.0,1485.0,210.0,3040.0
82,Mount Olive-Silverstone-Jamestown,2,NIA,32954.0,32788.0,0.5,10220.0,9875.0,7291.0,4.52,...,740.0,30700.0,18940.0,11755.0,6680.0,5075.0,1265.0,1050.0,215.0,3805.0
118,Thistletown-Beaumond Heights,3,NIA,10360.0,10138.0,2.2,3472.0,3280.0,3130.0,3.31,...,135.0,9550.0,7115.0,2435.0,1470.0,960.0,295.0,280.0,20.0,665.0
102,Rexdale-Kipling,4,No Designation,10529.0,10488.0,0.4,3989.0,3846.0,4229.0,2.49,...,115.0,9740.0,6535.0,3210.0,2270.0,945.0,450.0,405.0,40.0,490.0
39,Elms-Old Rexdale,5,NIA,9456.0,9550.0,-1.0,3344.0,3219.0,3306.0,2.86,...,125.0,8955.0,5970.0,2985.0,2135.0,850.0,395.0,265.0,120.0,455.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124,West Hill,136,NIA,27392.0,26547.0,3.2,10318.0,9986.0,2856.0,9.59,...,300.0,25525.0,17475.0,8050.0,5835.0,2210.0,1040.0,850.0,170.0,1180.0
133,Woburn,137,NIA,53485.0,53350.0,0.3,19098.0,18436.0,4345.0,12.31,...,1295.0,49910.0,30665.0,19235.0,11975.0,7260.0,1720.0,1400.0,335.0,5540.0
38,Eglinton East,138,NIA,22776.0,22829.0,-0.2,8199.0,7912.0,7051.0,3.23,...,515.0,21005.0,13115.0,7880.0,5050.0,2835.0,730.0,560.0,175.0,2100.0
109,Scarborough Village,139,NIA,16724.0,16609.0,0.7,6133.0,5923.0,5395.0,3.10,...,325.0,15375.0,9200.0,6170.0,4165.0,2005.0,560.0,415.0,160.0,1430.0
48,Guildwood,140,No Designation,9917.0,9816.0,1.0,4044.0,3991.0,2673.0,3.71,...,25.0,9220.0,6490.0,2730.0,2095.0,635.0,440.0,335.0,95.0,205.0

In [7]:
houseprice_csv = os.path.join(curr_dir, 'Resources', 'wellbeing-toronto-housing.csv')
houseprice_df = pd.read_csv(houseprice_csv)
houseprice_df.rename(columns = {'Neighbourhood Id':'Neighbourhood Number'}, inplace = True) 
houseprice_df['Neighbourhood Number'] = houseprice_df['Neighbourhood Number'].astype('int64')
houseprice_df.sort_values(by='Neighbourhood Number')
# houseprice_df['Neighbourhood Number'].dtype

,Neighbourhood,Neighbourhood Number,Home Prices,Mid-Century Highrise Households,Mid-Century Highrise Population,Percent Mid-Century Highrise Households,Percent Mid-Century Highrise Population,Rent Bank Applicants,Social Housing Turnover,Social Housing Units,Social Housing Waiting List
0,West Humber-Clairville,1,317508,690,1810,6.8,5.3,38,0.312500,952,557
1,Mount Olive-Silverstone-Jamestown,2,251119,4110,13395,42.9,40.9,41,7.000000,1146,1049
2,Thistletown-Beaumond Heights,3,414216,430,1260,13.4,12.4,7,1.333333,447,270
3,Rexdale-Kipling,4,392271,600,1050,15.2,10.0,19,4.200000,432,186
4,Elms-Old Rexdale,5,233832,870,2305,27.3,24.1,14,1.000000,463,239
...,...,...,...,...,...,...,...,...,...,...,...
135,West Hill,136,308229,3010,5880,31.1,22.1,22,8.400000,2089,725
136,Woburn,137,316584,5090,14870,27.8,27.9,26,4.911765,2660,1306
137,Eglinton East,138,274020,3935,10105,48.8,44.3,33,2.588235,865,688
138,Scarborough Village,139,356096,2905,7860,49.2,47.3,22,4.400000,922,683
139,Guildwood,140,444309,605,1020,15.3,10.4,3,0.000000,0,62

In [8]:
# Combine the data into a single dataset
# Merge on Neighbourhood Number
housing_df = pd.merge(census_df, houseprice_df, on='Neighbourhood Number', how='left')
housing_and_crime_df = pd.merge(housing_df, crime_df, on='Neighbourhood Number', how='left')
housing_and_crime_df
# print(housing_df.dtypes)
# print(housing_and_crime_df.dtypes)

,Neighbourhood_x,Neighbourhood Number,TSNS2020 Designation,"Population, 2016","Population, 2011",Population Change 2011-2016,Total private dwellings,Private dwellings occupied by usual residents,Population density per square kilometre,Land area in square kilometres,...,TheftOver_2016,TheftOver_2017,TheftOver_2018,TheftOver_2019,TheftOver_AVG,TheftOver_CHG,TheftOver_Rate_2019,Shape__Area,Shape__Length,geometry
0,Agincourt North,129,No Designation,29113.0,30279.0,-3.900,9371.0,9120.0,3929.0,7.41,...,5,11,4,2,4.7,-0.50,6.9,7.261857e+06,12381.264970,"{u'type': u'Polygon', u'coordinates': (((-79.2..."
1,Agincourt South-Malvern West,128,No Designation,23757.0,21988.0,8.000,8535.0,8136.0,3034.0,7.83,...,11,14,10,15,13.3,0.50,63.1,7.873163e+06,15386.556300,"{u'type': u'Polygon', u'coordinates': (((-79.2..."
2,Alderwood,20,No Designation,12054.0,11904.0,1.300,4732.0,4616.0,2435.0,4.95,...,10,7,7,7,6.8,0.00,58.1,4.978488e+06,9168.698727,"{u'type': u'Polygon', u'coordinates': (((-79.5..."
3,Annex,95,No Designation,30526.0,29177.0,4.600,18109.0,15934.0,10863.0,2.81,...,22,29,45,42,29.5,-0.07,137.6,2.790356e+06,7606.039230,"{u'type': u'Polygon', u'coordinates': (((-79.3..."
4,Banbury-Don Mills,42,No Designation,27695.0,26918.0,2.900,12473.0,12124.0,2775.0,9.98,...,11,5,8,14,10.3,0.75,50.6,1.004155e+07,18165.123920,"{u'type': u'Polygon', u'coordinates': (((-79.3..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135,Wychwood,94,No Designation,14349.0,13986.0,2.600,6185.0,5887.0,8541.0,1.68,...,4,4,2,0,2.3,-1.00,0.0,1.682111e+06,5435.021879,"{u'type': u'Polygon', u'coordinates': (((-79.4..."
136,Yonge-Eglinton,100,No Designation,11817.0,10578.0,0.117,6103.0,5676.0,7162.0,1.65,...,2,4,5,8,4.8,0.60,67.7,1.650438e+06,5686.684791,"{u'type': u'Polygon', u'coordinates': (((-79.4..."
137,Yonge-St.Clair,97,No Designation,12528.0,11652.0,0.075,7475.0,7012.0,10708.0,1.17,...,8,0,3,6,4.3,1.00,47.9,1.161315e+06,5873.270582,"{u'type': u'Polygon', u'coordinates': (((-79.3..."
138,York University Heights,27,NIA,27593.0,27713.0,-0.004,11051.0,10170.0,2086.0,13.23,...,37,39,38,28,36.3,-0.26,101.5,1.324666e+07,18504.777330,"{u'type': u'Polygon', u'coordinates': (((-79.5..."
139,Yorkdale-Glen Park,31,Emerging Neighbourhood,14804.0,14687.0,0.008,5847.0,5344.0,2451.0,6.04,...,26,23,20,29,22.5,0.45,195.9,6.038326e+06,10079.426920,"{u'type': u'Polygon', u'coordinates': (((-79.4..."

In [9]:
subset_df = housing_and_crime_df[['Neighbourhood Number','Neighbourhood_x',
'Population',
'Assault_2014',
'Assault_2015',
'Assault_2016',
'Assault_2017',
'Assault_2018',
'Assault_2019',
'Assault_AVG',
'Assault_CHG',
'Assault_Rate_2019',
'AutoTheft_2014',
'AutoTheft_2015',
'AutoTheft_2016',
'AutoTheft_2017',
'AutoTheft_2018',
'AutoTheft_2019',
'AutoTheft_AVG',
'AutoTheft_CHG',
'AutoTheft_Rate_2019',
'BreakandEnter_2014',
'BreakandEnter_2015',
'BreakandEnter_2016',
'BreakandEnter_2017',
'BreakandEnter_2018',
'BreakandEnter_2019',
'BreakandEnter_AVG',
'BreakandEnter_CHG',
'BreakandEnter_Rate_2019',
'Homicide_2014',
'Homicide_2015',
'Homicide_2016',
'Homicide_2017',
'Homicide_2018',
'Homicide_2019',
'Homicide_AVG',
'Homicide_CHG',
'Homicide_Rate_2019',
'Robbery_2014',
'Robbery_2015',
'Robbery_2016',
'Robbery_2017',
'Robbery_2018',
'Robbery_2019',
'Robbery_AVG',
'Robbery_CHG',
'Robbery_Rate_2019',
'TheftOver_2014',
'TheftOver_2015',
'TheftOver_2016',
'TheftOver_2017',
'TheftOver_2018',
'TheftOver_2019',
'TheftOver_AVG',
'TheftOver_CHG',
'TheftOver_Rate_2019',
'Shape__Area',
'Shape__Length',
'geometry',
'Population, 2016',
'Population, 2011',
'Population Change 2011-2016',
'Total private dwellings',
'Private dwellings occupied by usual residents',
'Population density per square kilometre',
'Land area in square kilometres',
'Occupied private dwellings by structural type of dwelling',
'Occupied private dwellings by structural type of dwelling|Single-detached house',
'Occupied private dwellings by structural type of dwelling|Apartment in a building that has five or more storeys',
'Occupied private dwellings by structural type of dwelling|Other attached dwelling',
'Occupied private dwellings by structural type of dwelling|Other attached dwelling|Semi-detached house',
'Occupied private dwellings by structural type of dwelling|Other attached dwelling|Row house',
'Occupied private dwellings by structural type of dwelling|Other attached dwelling|Apartment or flat in a duplex',
'Occupied private dwellings by structural type of dwelling|Other attached dwelling|Apartment in a building that has fewer than five storeys',
'Occupied private dwellings by structural type of dwelling|Other attached dwelling|Other single-attached house',
'Occupied private dwellings by structural type of dwelling|Movable dwelling',
'Private households by household size',
'Private households by household size|1 person',
'Private households by household size|2 persons',
'Private households by household size|3 persons',
'Private households by household size|4 persons',
'Private households by household size|5 or more persons',
'Number of persons in private households',
'Average household size',
'Total - Income statistics in 2015 for private households by household size - 100% data',
'Total - Income statistics in 2015 for private households by household size - 100% data|Median total income of households in 2015 ($)',
'Total - Income statistics in 2015 for private households by household size - 100% data|Median after-tax income of households in 2015 ($)',
'Total - Income statistics in 2015 for private households by household size - 100% data|Median after-tax income of households in 2015 ($)|Total - Income statistics in 2015 for one-person private households - 100% data',
'Total - Income statistics in 2015 for private households by household size - 100% data|Median after-tax income of households in 2015 ($)|Total - Income statistics in 2015 for one-person private households - 100% data|Median after-tax income of one-person households in 2015 ($)',
'Total - Income statistics in 2015 for private households by household size - 100% data|Median after-tax income of households in 2015 ($)|Total - Income statistics in 2015 for two-or-more-person private households - 100% data',
'Total - Income statistics in 2015 for private households by household size - 100% data|Median after-tax income of households in 2015 ($)|Total - Income statistics in 2015 for two-or-more-person private households - 100% data|Median total income of two-or-more-person households in 2015 ($)',
'Total - Income statistics in 2015 for private households by household size - 100% data|Median after-tax income of households in 2015 ($)|Total - Income statistics in 2015 for two-or-more-person private households - 100% data|Median after-tax income of two-or-more-person households in 2015 ($)',
'Total - Income statistics in 2015for private households by household size - 25% sampledata',
'Total - Income statistics in 2015for private households by household size - 25% sampledata|Average total income of households in 2015 ($)',
'Total - Income statistics in 2015for private households by household size - 25% sampledata|Average after-tax income of households in 2015 ($)',
'Total - Income statistics in 2015for private households by household size - 25% sampledata|Average after-tax income of households in 2015 ($)|Total - Income statistics in 2015 for one-person private households - 25% sample data',
'Total - Income statistics in 2015for private households by household size - 25% sampledata|Average after-tax income of households in 2015 ($)|Total - Income statistics in 2015 for one-person private households - 25% sample data|Average total income of one-person households in 2015 ($)',
'Total - Income statistics in 2015for private households by household size - 25% sampledata|Average after-tax income of households in 2015 ($)|Total - Income statistics in 2015 for one-person private households - 25% sample data|Average after-tax income of one-person households in 2015 ($)',
'Total - Income statistics in 2015for private households by household size - 25% sampledata|Average after-tax income of households in 2015 ($)|Total - Income statistics in 2015 for two-or-more-person private households - 25% sample data',
'Total - Income statistics in 2015for private households by household size - 25% sampledata|Average after-tax income of households in 2015 ($)|Total - Income statistics in 2015 for two-or-more-person private households - 25% sample data|Average total income of two-or-more-person households in 2015 ($)',
'Total - Income statistics in 2015for private households by household size - 25% sampledata|Average after-tax income of households in 2015 ($)|Total - Income statistics in 2015 for two-or-more-person private households - 25% sample data|Average after-tax income of two-or-more-person households in 2015 ($)',
'Total - Household total income groups in 2015 for private households - 100% data',
'Total - Household total income groups in 2015 for private households - 100% data|Under $5,000',
'Total - Household total income groups in 2015 for private households - 100% data|$5,000 to $9,999',
'Total - Household total income groups in 2015 for private households - 100% data|$10,000 to $14,999',
'Total - Household total income groups in 2015 for private households - 100% data|$15,000 to $19,999',
'Total - Household total income groups in 2015 for private households - 100% data|$20,000 to $24,999',
'Total - Household total income groups in 2015 for private households - 100% data|$25,000 to $29,999',
'Total - Household total income groups in 2015 for private households - 100% data|$30,000 to $34,999',
'Total - Household total income groups in 2015 for private households - 100% data|$35,000 to $39,999',
'Total - Household total income groups in 2015 for private households - 100% data|$40,000 to $44,999',
'Total - Household total income groups in 2015 for private households - 100% data|$45,000 to $49,999',
'Total - Household total income groups in 2015 for private households - 100% data|$50,000 to $59,999',
'Total - Household total income groups in 2015 for private households - 100% data|$60,000 to $69,999',
'Total - Household total income groups in 2015 for private households - 100% data|$70,000 to $79,999',
'Total - Household total income groups in 2015 for private households - 100% data|$80,000 to $89,999',
'Total - Household total income groups in 2015 for private households - 100% data|$90,000 to $99,999',
'Total - Household total income groups in 2015 for private households - 100% data|$100,000 and over',
'Total - Household total income groups in 2015 for private households - 100% data|$100,000 and over|$100,000 to $124,999',
'Total - Household total income groups in 2015 for private households - 100% data|$100,000 and over|$125,000 to $149,999',
'Total - Household total income groups in 2015 for private households - 100% data|$100,000 and over|$150,000 to $199,999',
'Total - Household total income groups in 2015 for private households - 100% data|$100,000 and over|$200,000 and over',
'Total - Private households by tenure - 25% sample data',
'Total - Private households by tenure - 25% sample data|Owner',
'Total - Private households by tenure - 25% sample data|Renter',
'Total - Occupied private dwellings by condominium status - 25% sample data',
'Total - Occupied private dwellings by condominium status - 25% sample data|Condominium',
'Total - Occupied private dwellings by condominium status - 25% sample data|Not condominium',
'Total - Occupied private dwellings by number of bedrooms - 25% sample data',
'Total - Occupied private dwellings by number of bedrooms - 25% sample data|No bedrooms',
'Total - Occupied private dwellings by number of bedrooms - 25% sample data|1 bedroom',
'Total - Occupied private dwellings by number of bedrooms - 25% sample data|2 bedrooms',
'Total - Occupied private dwellings by number of bedrooms - 25% sample data|3 bedrooms',
'Total - Occupied private dwellings by number of bedrooms - 25% sample data|4 or more bedrooms',
'Total - Occupied private dwellings by number of rooms - 25% sample data',
'Total - Occupied private dwellings by number of rooms - 25% sample data|1 to 4 rooms',
'Total - Occupied private dwellings by number of rooms - 25% sample data|5 rooms',
'Total - Occupied private dwellings by number of rooms - 25% sample data|6 rooms',
'Total - Occupied private dwellings by number of rooms - 25% sample data|7 rooms',
'Total - Occupied private dwellings by number of rooms - 25% sample data|8 or more rooms',
'Total - Private households by number of persons per room - 25% sample data',
'Total - Private households by number of persons per room - 25% sample data|Major repairs needed',
'Total - Private households by number of persons per room - 25% sample data|One person or fewer per room',
'Total - Private households by number of persons per room - 25% sample data|More than 1 person per room',
'Total - Private households by housing suitability - 25% sample data',
'Total - Private households by housing suitability - 25% sample data|Suitable',
'Total - Private households by housing suitability - 25% sample data|Not suitable',
'Total - Occupied private dwellings by period of construction - 25% sample data',
'Total - Occupied private dwellings by period of construction - 25% sample data|1960 or before',
'Total - Occupied private dwellings by period of construction - 25% sample data|1961 to 1980',
'Total - Occupied private dwellings by period of construction - 25% sample data|1981 to 1990',
'Total - Occupied private dwellings by period of construction - 25% sample data|1991 to 2000',
'Total - Occupied private dwellings by period of construction - 25% sample data|2001 to 2005',
'Total - Occupied private dwellings by period of construction - 25% sample data|2006 to 2010',
'Total - Occupied private dwellings by period of construction - 25% sample data|2011 to 2016',
'Total - Occupied private dwellings by dwelling condition - 25% sample data',
'Total - Occupied private dwellings by dwelling condition - 25% sample data|Only regular maintenance or minor repairs needed',
'Total - Private households by number of household maintainers - 25% sample data',
'Total - Private households by number of household maintainers - 25% sample data|1 household maintainer',
'Total - Private households by number of household maintainers - 25% sample data|2 household maintainers',
'Total - Private households by number of household maintainers - 25% sample data|3 or more household maintainers',
'Total - Private households by age of primary household maintainers - 25% sample data',
'Total - Private households by age of primary household maintainers - 25% sample data|15 to 24 years',
'Total - Private households by age of primary household maintainers - 25% sample data|25 to 34 years',
'Total - Private households by age of primary household maintainers - 25% sample data|35 to 44 years',
'Total - Private households by age of primary household maintainers - 25% sample data|45 to 54 years',
'Total - Private households by age of primary household maintainers - 25% sample data|55 to 64 years',
'Total - Private households by age of primary household maintainers - 25% sample data|65 to 74 years',
'Total - Private households by age of primary household maintainers - 25% sample data|75 to 84 years',
'Total - Private households by age of primary household maintainers - 25% sample data|85 years and over',
'Total - Private households by age of primary household maintainers - 25% sample data|Total - Owner and tenant households with household total income greater than zero; in non-farm; non-reserve private dwellings by shelter-cost-to-income ratio - 25% sample data',
'Total - Private households by age of primary household maintainers - 25% sample data|Spending less than 30% of income on shelter costs',
'Total - Private households by age of primary household maintainers - 25% sample data|Spending 30% or more of income on shelter costs',
'Total - Private households by age of primary household maintainers - 25% sample data|Spending 30% or more of income on shelter costs|30% to less than 100%'
]]
subset_df

,Neighbourhood Number,Neighbourhood_x,Population,Assault_2014,Assault_2015,Assault_2016,Assault_2017,Assault_2018,Assault_2019,Assault_AVG,...,Total - Private households by age of primary household maintainers - 25% sample data|35 to 44 years,Total - Private households by age of primary household maintainers - 25% sample data|45 to 54 years,Total - Private households by age of primary household maintainers - 25% sample data|55 to 64 years,Total - Private households by age of primary household maintainers - 25% sample data|65 to 74 years,Total - Private households by age of primary household maintainers - 25% sample data|75 to 84 years,Total - Private households by age of primary household maintainers - 25% sample data|85 years and over,Total - Private households by age of primary household maintainers - 25% sample data|Total - Owner and tenant households with household total income greater than zero; in non-farm; non-reserve private dwellings by shelter-cost-to-income ratio - 25% sample data,Total - Private households by age of primary household maintainers - 25% sample data|Spending less than 30% of income on shelter costs,Total - Private households by age of primary household maintainers - 25% sample data|Spending 30% or more of income on shelter costs,Total - Private households by age of primary household maintainers - 25% sample data|Spending 30% or more of income on shelter costs|30% to less than 100%
0,129,Agincourt North,29113,67,76,77,71,79,79,74.8,...,1240.0,2145.0,2050.0,1535.0,995.0,380.0,9110.0,5960.0,3155.0,2690.0
1,128,Agincourt South-Malvern West,23757,107,112,136,115,114,123,117.8,...,1195.0,1835.0,1625.0,1200.0,695.0,240.0,8105.0,4990.0,3120.0,2465.0
2,20,Alderwood,12054,45,47,39,21,30,36,36.3,...,895.0,985.0,1005.0,590.0,460.0,220.0,4610.0,3610.0,1005.0,875.0
3,95,Annex,30526,213,226,257,248,246,288,246.3,...,2385.0,2295.0,2180.0,1925.0,1135.0,390.0,15855.0,9435.0,6445.0,4615.0
4,42,Banbury-Don Mills,27695,61,78,84,109,77,74,80.5,...,1855.0,2570.0,2165.0,1870.0,1460.0,850.0,12085.0,8040.0,4045.0,3340.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135,94,Wychwood,14349,54,76,86,55,76,74,70.2,...,960.0,1155.0,955.0,725.0,535.0,210.0,5870.0,3775.0,2095.0,1780.0
136,100,Yonge-Eglinton,11817,64,64,73,73,78,103,75.8,...,1130.0,970.0,930.0,685.0,305.0,120.0,5670.0,3740.0,1925.0,1465.0
137,97,Yonge-St.Clair,12528,20,29,39,27,34,37,31.0,...,1030.0,1185.0,1050.0,1060.0,620.0,290.0,7020.0,4485.0,2535.0,1955.0
138,27,York University Heights,27593,271,296,361,344,357,370,333.2,...,1760.0,2065.0,1660.0,1090.0,785.0,290.0,10145.0,6070.0,4080.0,3375.0
139,31,Yorkdale-Glen Park,14804,106,136,174,161,175,209,160.2,...,890.0,1090.0,1000.0,685.0,630.0,325.0,5335.0,3700.0,1645.0,1400.0